---
version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: chore
      include: scope
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"