name: PR checks

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    if: always() && !github.event.pull_request.draft
    env:
      GOPRIVATE: github.com/molotovtv
      GH_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: ⭐️ Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

      - name: Install dependencies
        run: go get ./...

      - name: ✅ Tests
        run: |
          go test ./...
